### ISSUE TITLE
Edamam calories wrong query results

### ISSUE THREAD

**Issue by Knodeln** [chrille0313/DishPlanner#22]
**Describe the bug**
Querying the edamam API with calories as a parameter doesn't work as documented on website. No current fix.

**To Reproduce**
Query the API with calories as a parameter with MAX, MIN or RANGE

**Expected behavior**
A return of recipes within the specified calorie amount.

**Comment by chrille0313** [comment]
The calories query is per serving as documented on the api website:
![image](https://github.com/chrille0313/DishPlanner/assets/47303717/a718b5f5-93a5-4931-87bf-641a8b295cbe)

I did not manage to reproduce this error with my testing.
